baseurl = "https://docs.flyntwp.com/"
languageCode = "en-us"
title = "Flynt Framework"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[params]
  # General information
  author = "Bleech GmbH"
  description = "The component based WordPress framework for development teams and their clients."
  copyright = "Released under the MIT license"

  # Repository
  provider = "GitHub"
  repo_url = "https://github.com/flyntwp/flynt-starter-theme"

  version = "0.1.0"
  logo = "images/logo.jpg"
  favicon = "favicon.ico"

  permalink = "#"

  # Custom assets
  custom_css = [
    'styles/website.css'
  ]
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  [params.palette]
      primary = "teal"
      accent  = "blue-grey"

    [params.font]
      text = "Ubuntu"
      code = "Ubuntu Mono"


[social]
  twitter = "flyntwp"
  github  = "flyntwp"
  email   = "flynt@bleech.de"

[[menu.main]]
  name   = "Documentation"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Getting Started"
  url    = "getting-started/"
  weight = 10

[[menu.main]]
  name   = "Tutorial: Build your first Component"
  url    = "tutorial/"
  weight = 20

[[menu.main]]
  name   = "Components"
  url    = "components/"
  weight = 30

[[menu.main]]
  name   = "Features"
  url    = "features/"
  weight = 40

[[menu.main]]
  name   = "WordPress"
  url    = "wordpress/"
  weight = 50

[[menu.main]]
  name   = "Utils"
  url    = "utils/"
  weight = 60

[[menu.main]]
  name   = "Core"
  url    = "core/"
  weight = 70

[[menu.main]]
  name   = "CLI"
  url    = "cli/"
  weight = 80

[[menu.main]]
  name   = "Meta"
  url    = "meta/"
  weight = 90

[blackfriday]
  smartypants	= true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
