baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "Flynt Framework"
metadataformat = "yaml"
canonifyurls = true
relativeURLs = true

[params]
  # General information
  author = "bleech GmbH"
  description = "The component based WordPress framework for development teams and their clients."
  copyright = "Released under the MIT license"
  version = "0.1.0"
  logo = "images/logo.svg"
  favicon = "/images/favicon.ico"
  googleAnalytics = "UA-88576792-2"

[params.repo]
  theme_url = "https://github.com/flyntwp/flynt-starter-theme"
  docs_url = "https://github.com/flyntwp/flynt-docs"
  organisation_url = "https://github.com/flyntwp"

[params.social]
  twitter = "flyntwp"

# Top Menu Items
[[menu.main]]
  name   = "Guide"
  url    = "/guide/getting-started/what-is-flynt/"
  weight = 20

[[menu.main]]
  name   = "Flynt Website"
  url    = "https://flyntwp.com"
  weight = 40

# Side Menu Items, Parent should match the identifier of the Top Menu Item
[[menu.main]]
  name   = "Getting Started"
  url    = "/guide/getting-started/"
  parent = "Guide"
  weight = 10

[[menu.main]]
  name   = "Configuration"
  identifier = "configuration"
  url    = "/guide/configuration/"
  parent = "Guide"
  weight = 20

[[menu.main]]
  name   = "Components"
  identifier = "components"
  url    = "/guide/components/"
  parent = "Guide"
  weight = 30

[[menu.main]]
  name   = "Features"
  url    = "/guide/features/"
  parent = "Guide"
  weight = 40

[[menu.main]]
  name   = "Utils"
  url    = "/guide/utils/"
  parent = "Guide"
  weight = 50

[[menu.main]]
  name   = "Core Plugin"
  identifier = "core"
  url    = "/guide/core/"
  parent = "Guide"
  weight = 60

[[menu.main]]
  name   = "Best Practices"
  url    = "/guide/best-practices/"
  parent = "Guide"
  weight = 70

[[menu.main]]
  name   = "Resources"
  identifier = "resources"
  url    = "/guide/resources/"
  parent = "Guide"
  weight = 80
